kind: pipeline
type: docker
name: 腾讯云对象存储插件


clone:
  disable: true


trigger:
  event:
    exclude:
      - pull_request


steps:
  - name: 拉代码
    image: ccr.ccs.tencentyun.com/dronestock/git

  - name: 编译
    image: ccr.ccs.tencentyun.com/pangum/drone
    settings:
      output: cos

  - name: 发布
    image: ccr.ccs.tencentyun.com/dronestock/docker
    privileged: true
    volumes:
      - name: cache
        path: /var/lib/docker
    environment:
      PASSWORD_DOCKER:
        from_secret: token_docker
      PASSWORD_CCR:
        from_secret: password_tencentyun_ccr
    settings:
      repository: dronestock/cos
      registries:
        - username: dronestock
          password: $${PASSWORD_DOCKER}
        - hostname: ccr.ccs.tencentyun.com
          username: "160290688"
          password: $${PASSWORD_CCR}
          required: true


volumes:
  - name: cache
    host:
      path: /var/lib/cache/docker
